---
stages:
  - commands:
      - executionInstructions: "dotnet build"
        name: Build
        order: 1
        type: shell
      - executionInstructions: "dotnet run"
        name: Run
        order: 2
        type: shell
      - executionInstructions: "C:\\Windows\\System32\\cmd.exe"
        name: Cmd
        order: 3
        type: process
        arguments:
            - echo
            - process test
    name: Build
